name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on the main branch (adjust if your default branch is different)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19.0'  # Use the Node.js version compatible with your Angular app

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build --prod -- --base-href ""

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main  # Target branch for GitHub Pages
          folder: app-api  # Folder with the built Angular app

